name: Check Python application

on: [push]

env:
  MIN_COVERAGE_REQUIRED: 75

jobs:
  python-test-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    
    - name: Set up Python 3.10.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip freeze > requirements.txt
    - name: Github Action for testing the code
      run: coverage run -m unittest discover

    - name: Github Action to retrieve coverage percentage
      id: total-coverage
      run: |
        coverage json -q -o /dev/stdout | python -c 'import sys, json; perc_cov = json.load(sys.stdin)["totals"]["percent_covered"]; is_covered = perc_cov >= '$MIN_COVERAGE_REQUIRED'; print("Coverage is: ", perc_cov); sys.exit(not is_covered)'
